# Generated by Django 4.2.6 on 2023-10-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
